### PR TITLE
The Next Web - Clone

### PR DESCRIPTION
**Pull request by smy5152**
Dear Reviewer,
Looking forward to your feedback and improvement suggestions for the project.

**Learning Goals**

- HTML5
- CSS3
- Responsive Web page design and project completion.

Thanks

### CODE REVIEW

**Comment by descholar-ceo** [comment]
# This Pull Request is under review by [descholar-ceo](https://github.com/descholar-ceo) :eyes: :eyes: 
## Please wait a bit ...

**Review by descholar-ceo — CHANGES_REQUESTED** [review]
# Status: Changes Required :vertical_traffic_light: :warning: 
## Hello @chuckbuckethead and @smy5152  :handshake: :handshake: :handshake: 

:+1: This is good to make it this far, your clone is almost looking like the original page and it is really nice, congratulations on the good work you have done so far.
:+1: I liked that you have tried to implement all of the requirements carefully, keep it up, and your project is really almost done.
#### :warning: However we need to make few changes to mark this project approved. See the requested change below :point_down: :point_down: :point_down: 
### Note: All of requested changes which are marked as [Required] are mandatory to be implemented in order to get this project approved, others which are marked as [Optional] are nice to have in your project to make it outstanding

# [Required Changes] :red_circle: 
## Maintaining professional repository

- [x] Fix the issue link from the readme file
- [x] The social media links of the `Author 2` are all broken, fix that as well
- [x] Fix the linkedin profile link of `Shabbir`
- [x] The screenshot is broken in readme file, fix that by providing the right screenshot path
- [x] The live demo link is broken, please fix that as well

## General

- [x] The navbar is missing the yellow small navbar 

| Your clone | Original page |
| --- | --- |
| Screenshot from 2021-01-20 21-18-18 | Screenshot from 2021-01-20 21-19-25 |

:point_right: Could you see the difference :question: :question: :question: 

- [x] The navbar is missing a search icon on the right most side
- [x] The top three articles (On the left most big article) they are not simulating the original articles from the original page, work on them again: add gradient, and TNW logo for the large screens which disappears on medium screens 

| Your clone | Original page |
| --- | --- |
| Screenshot from 2021-01-21 07-17-37 | Screenshot from 2021-01-21 07-18-04 |

:point_right: Could you see the difference :question: :question: :question: 

- [x] All images of the top three articles should take the maximum width and are are aligned in one column on mobile screens
- [x] TWN logo should appear at the leftmost part of the navbar on medium screens
- [x] Navigation and sub-navigation row should change to a hamburger (bars) icon at the rightmost part (next to seach icon) on mobile screens
- [x] The latest news section should align 3 articles per row on medium screens
- [x] The latest new section should align 1 articles per row on mobile screens (mobile screens start from 768px) yours is starting from 600px => that's wrong
- [x] The latest funding section should align 3 articles per row on medium screens
- [x] The latest funding section (title) is missing the right most three options please add them
- [x] The latest funding section should align 1 category box per row (the mobile screen starts from 768px) yours is starting from 600px => this is wrong
- [x] The latest deals section should align 3 deals per row in medium screens

:warning: _As a note and hint, there is a general issue I noticed in your project, the breakpoints should be as follow: large screens have min-width of 1024px, medium screens have min-width of 768px_

## Codes

- [x] The linters errors you have are all fixable, please fix them before the other code review request
- [x]  It’s better to delete commented piece of codes. If you need to review a previous version of your code, use git history ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/general/no_inline_comments.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/66243643/))
- [x] The main concern as the aim of this project was to go mobile first approach, you should have followed that requirement [screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/html_css/responsive_design/mobile_first.png) from the pathwright, please refer to [this article](https://zellwk.com/blog/how-to-write-mobile-first-css/) to know how you should go mobile first approach
- [x] You have some CSS codes which are being repeated several time `eg: visibility: hidden; => repeated 2 times`, that is a bad practice, to avoid that you can create utility classes which hold the property that you see that is needed on multiple elements and then apply that class to those elements. Please look for all of the repeated codes and fix them like that.

___
_If anything seems to be unclear to you, reachout and ask anything by commenting on this Pull Request and mention me as [descholar-ceo](https://github.com/descholar-ceo), I will receive a notification and will respond._

[GitHub](https://github.com/descholar-ceo) | [LinkedIn](https://linkedin.com/in/mugirase-emmanuel) | [Twitter](https://twitter.com/descholar3)

_Reviewed by [Mugirase Emmanuel (descholar)](https://github.com/descholar-ceo)_

**Comment by smy5152** [comment]
Thanks and appreciate the detailed feedback. The check-list was very helpful in fixing every small detail 1 at a time. 
All listed checkpoints are complete and many other decorative and critical bugs as well as layouts fixed.

**Review by kobiyoyo — CHANGES_REQUESTED** [review]
## Hi Team     
#### Great Job so far, everything works fine, but there are a few more things required. 
### General

  - [x]  In the latest funding section for the medium screen you are to display 3 elements, not 4.(Note: this is the same for the small screen )
  Yours 


Original



### Make changes and submit another code review request.
*Happy coding* 
(Any questions Feel free to contact me on slack @kobiyoyo)

**Comment by smy5152** [comment]
@kobiyoyo 
Amazing. 

Thank you for the prompt and detailed review.

We have done the changes and resubmitted the review request.

Thanks and Warm Regards

**Review by voscarmv — CHANGES_REQUESTED** [review]
# Impressive work, team. 💻 👀 ✨ 

## However, there are some changes required 👀 🧰 🔨 🔧 
- The images on your design become stretched on Tablet and Mobile views. Please fix this:
image

- Great work using semantic HTML. No changes required there :)
### Submit these changes and request a new code review! 😄 👍 

### Questions or comments? Reach me on [Twitter](https://twitter.com/voscarmv) or [LinkedIn](https://linkedin.com/in/oscar-mier) 🧑‍💻🗨️🧑‍💻 
# Happy Hacking! 🧠 ⌨️ 🖱️ 🖥️

**Comment by crgc** [comment]
Thank you for the review @voscarmv. We have implemented your recommendations and requested a new code review.

**Review by arslanbisharat — APPROVED** [review]
# Approved :smile: 

Hello Developer :wave:

I just reviewed your project and I am very happy to inform you that your project is approved.
Congratulations on achieving this milestone in your career. :clap:


_I am looking forward to seeing your next project._

Stay safe and give me a smile 😇

### Happy Coding
------------------------------------------------------------------------------------------------
**Regards,
Arslan Bisharat
slack: arslanbisharat**

**Comment by smy5152** [comment]
Thanks @Arslan, your effort and method of feedback in the 1st project set up the process and steps we stick to to meet our goals before the last moment.

Appreciate and Grateful for the work of all Reviewers on the project. 

Regards,
Micronauts - Shabbir & Carlos

**Pull request merged**
